### PR TITLE
Update New Icons and Add Logo Files

### PR DESCRIPTION
**Pull request by zularizal**

### CODE REVIEW

**Comment by Davidodari** [comment]
@zularizal thanks for the logos, ill add an acknowledgement section for logo design

**Comment by zularizal** [comment]
Okay. Can I make a logo on your other open source projects?

I like to make logos / icons and you don't have to pay for this.

**Comment by Davidodari** [comment]
Yeah @zularizal you can get on any of the projects ,do you have any other social platform someone can reach you on?

**Comment by zularizal** [comment]
Yes @Davidodari , someone can contact me via telegram or my email.
https://t.me/zularizal
faimast1@gmail.com

**Pull request merged**
